---
namespace: community
name: docker_role
version: 1.0.0
readme: README.md
authors:
  - Daniel JOSEPH
description: Installation de docker
license_file: BSD
tags:
  - v1
repository: https://github.com/lianhuahayu/docker_role.git
documentation: https://github.com/lianhuahayu/docker_role.git
homepage: https://github.com/lianhuahayu/docker_role.git
issues: https://github.com/lianhuahayu/docker_role.git
build_ignore:
  - .gitignore
 